simple:
	x86_64-w64-mingw32-g++ -o build/simple.exe simple_read.c
	wine build/simple.exe

async:
	x86_64-w64-mingw32-g++ -o build/async.exe async_read.c
	wine build/async.exe

thread:
	x86_64-w64-mingw32-g++ -o build/thread.exe thread_read.c
	wine build/thread.exe
